# Generated by Django 3.2.7 on 2021-09-19 13:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID('a8950079-4c1c-4c29-825b-ef3dc8189d04'), editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('body', models.TextField(blank=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'шаблоны',
                'db_table': 'message_template',
            },
        ),
        migrations.CreateModel(
            name='NotifyHistory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID('85b7c903-82d3-4f6d-8c9d-e50c34680815'), editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('notification_id', models.CharField(max_length=255, verbose_name='идентификатор оповещения')),
            ],
            options={
                'verbose_name': 'история оповещений',
                'verbose_name_plural': 'история оповешений',
            },
        ),
    ]
