# Generated by Django 3.1 on 2021-09-19 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20210919_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyhistory',
            options={'verbose_name': 'история оповещений', 'verbose_name_plural': 'история оповещений'},
        ),
        migrations.RemoveField(
            model_name='notifyhistory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notifyhistory',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='notifyhistory',
            name='notification_id',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('websocket', 'Websocket')], default='email', max_length=20, verbose_name='способ связи'),
        ),
        migrations.AddField(
            model_name='notifyhistory',
            name='body',
            field=models.TextField(blank=True, verbose_name='текст сообщения'),
        ),
        migrations.AddField(
            model_name='notifyhistory',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('websocket', 'Websocket')], default='email', max_length=20, verbose_name='способ связи'),
        ),
        migrations.AddField(
            model_name='notifyhistory',
            name='send_time',
            field=models.DateField(null=True, verbose_name='дата отправки'),
        ),
        migrations.AddField(
            model_name='notifyhistory',
            name='service',
            field=models.CharField(max_length=80, null=True, verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='notifyhistory',
            name='type',
            field=models.CharField(max_length=80, null=True, verbose_name='тип сообщения'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(verbose_name='шаблон'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6680338-2d5e-4358-a1ec-64536c5138fa'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(max_length=80, verbose_name='тип сообщения'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('213dc56a-5840-406b-8381-d5ec9fd31932'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
