# Generated by Django 3.1 on 2021-09-20 19:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20210919_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='sender',
            field=models.CharField(default='admin', max_length=80, verbose_name='отправитель'),
        ),
        migrations.AddField(
            model_name='notifyhistory',
            name='recipient',
            field=models.CharField(default='nobody@email.com', max_length=80, verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7be0c00f-c2cf-41d8-aacb-c9d598f29db6'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(default='', max_length=80, verbose_name='тип сообщения'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='body',
            field=models.TextField(verbose_name='текст сообщения'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('994de4f5-0390-4ad0-9b19-ed8989e115fa'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата отправки'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='service',
            field=models.CharField(default='admin', max_length=80, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='type',
            field=models.CharField(default='email', max_length=80, verbose_name='тип сообщения'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('channel', 'type')},
        ),
        migrations.AlterModelTable(
            name='notifyhistory',
            table='message_history',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='title',
        ),
    ]
