# Generated by Django 3.2.7 on 2021-09-20 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20210919_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11b3a198-781b-469c-92f4-549e37079330'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ddaf42f-d42c-465b-b5dc-ee55b6fce7f9'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterModelTable(
            name='notifyhistory',
            table='message_history',
        ),
    ]
