# Generated by Django 3.2.7 on 2021-09-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20210920_1945'),
        ('notify', '0005_auto_20210920_2251'),
    ]

    operations = [
    ]
