# Generated by Django 3.2.7 on 2021-09-20 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_merge_0005_auto_20210920_1945_0005_auto_20210920_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35e1069e-a5ba-4fa0-8c6b-af6758504140'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4633daf5-e539-4f4b-864f-c940812590b0'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
