# Generated by Django 3.2.7 on 2021-09-22 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20210920_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='subject',
            field=models.CharField(default='', max_length=80, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1683c7c-8c12-4eb2-acf0-93375b4b36ac'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ff82326-3e9a-45a5-ac9f-e5b4a458211f'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
