# Generated by Django 3.2.7 on 2021-09-25 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0008_auto_20210922_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyhistory',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c476d02-882c-4bd7-b795-2a9968458c2e'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='notifyhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ae99e11-ebbf-4b33-ba2f-1f1fbef5bdcd'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
