version: '3.8'

x-env: &x-env
  env_file:
  - env

services:

  notif-api:
    build: ./notif_api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./notif_api:/app
    depends_on:
      - rabbit
    <<: *x-env

  notif-admin:
    build: ./admin
    ports:
      - "8001:8001"
    volumes:
      - ./admin:/app/
      - static_volume:/usr/app/config/static:ro
    depends_on:
      - notif-admin-db
    <<: *x-env

  notif-admin-db:
    restart: unless-stopped
    container_name: notif-admin-db
    image: library/postgres:13.2
    ports:
    - "5432:5432"
    volumes:
    - postgresdata:/var/lib/postgresql/data
    <<: *x-env

  celery:
    build: ./admin
    volumes:
      - ./admin:/admin
    depends_on:
      - notif-api
      - rabbit
    environment:
      - WORKER_CONTAINER=TRUE
    <<: *x-env

  rabbit:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    <<: *x-env

volumes:
  postgresdata:
  static_volume:
