version: '3.8'

x-env: &x-env
  env_file:
  - env

services:

  notif-api:
    build: ./notif_api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./notif_api:/app
    depends_on:
      - rabbit
    <<: *x-env

  notif-admin:
    build: ./admin
    command: >
      sh -c "
      gunicorn config.wsgi:application -t 300 -w 4 -b 0.0.0.0:80 --reload --access-logfile - --error-logfile"
    ports:
      - "8001:8001"
    volumes:
      - ./admin:/app/
      - static_volume:/usr/app/config/static:ro
    depends_on:
      - notif-admin-db
    <<: *x-env

  celery:
    build: ./admin
    volumes:
      - ./admin:/admin
    depends_on:
      - notif-api
      - rabbit
    environment:
      - WORKER_CONTAINER=TRUE

  rabbit:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    env_file:
      - env

  notify-db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    env_file:
      - env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgresdata:
  static_volume:
