version: '3.8'

services:
  rabbit:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    env_file:
      - env

  notify-db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    env_file:
      - env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgresdata: