version: '3.8'

x-env: &x-env
  env_file:
  - env

services:

  notif-api:
    build: ./notify_api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./notify_api:/app
    depends_on:
      - rabbit
    <<: *x-env

  notif-admin:
    build: ./admin
    ports:
      - "8001:8001"
    volumes:
      - ./admin:/app/
      - static_volume:/usr/app/config/static:ro
    depends_on:
      - notif-admin-db
    <<: *x-env

  notify-db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: on-failure
    <<: *x-env

  worker:
    build: ./senders
    command: celery -A sender_worker worker --loglevel=info
    volumes:
      - ./senders:/app
    depends_on:
      - notif-api
      - rabbit
    <<: *x-env

  scheduler:
    build: ./senders
    command: celery -A sender_worker beat -l INFO
    volumes:
      - ./senders:/app
    depends_on:
      - notif-api
      - rabbit
    <<: *x-env

  rabbit:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    <<: *x-env

volumes:
  postgresdata:
  static_volume:
