name: Python application

on:
  push:
    branches: "**"
  pull_request:
    branches: "main"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy --skip-lock

      - name: Linters
        run: |
          git diff origin/main | flake8 --diff

      - name: Check typing
        if: always()
        run: |
          mypy -v $(git diff origin/main --name-only '*.py') || $(find . -type f -name "*.py")

      - name: Deploy to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  conclude:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The ${{ github.event_name }} event finished with result ${{ env.WORKFLOW_CONCLUSION }}
        if: env.WORKFLOW_CONCLUSION == 'success'

